DROP TABLE IF EXISTS products;

CREATE TABLE products (
  id INT PRIMARY KEY,
  sku VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  category VARCHAR(250) NOT NULL,
  price INTEGER NOT NULL
);

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;